---
name: DoorBell
main: DataLion\DoorBell\Main
version: 1.1.2
api: 5.0.0
author: DataLion
description: Super Simple Doorbell plugin
commands:
  createdoorbell:
    permission: createdoorbell.command
    description: Create a doorbell
permissions:
  createdoorbell.command:
    description: Create a doorbell perm
    default: op
...
